export const SCREEN_PADDING_HORIZONTAL_STANDARD_VALUE = 18;
export const SCREEN_PADDING_VERTICAL_STANDARD_VALUE = 10;
export const TOAST_DEFAULT_OFFSET = 150;
export const TOAST_DEFAULT_VISIBILITY_TIME = 2000;
